backend:
  name: git-gateway
  branch: main

media_folder: uploads

collections:
  - name: config
    label: Mon portfolio
    files:
      - name: settings
        label: Textes & paramètres
        file: _data/settings.json
        fields:
          - {label: Nom, name: name, widget: string}
          - {label: Sous-titre, name: subtitle, widget: string}
          - {label: Description accueil, name: desc, widget: text}
          - {label: Email, name: email, widget: string}
          - {label: LinkedIn URL, name: linkedin, widget: string, required: false}
          - {label: Instagram URL, name: instagram, widget: string, required: false}
          - {label: À propos paragraphe 1, name: about1, widget: text}
          - {label: À propos paragraphe 2, name: about2, widget: text}
